parameters:
    name:                   'Blurp'
    color:                  'C8201B'
    images:
        avatar:             'images/sako-01.jpg'
    metas:
        title:              'Blurp Bundle'
        author:             'Giancarlo PALUMBO'
        email:              'giancarlo.palumbo@free.fr'
        description:        "Template for Marvel's Website by Symfony 7.4.X"
        generator:          'PHPStorm'

when@dev:
    parameters:
        images:
            logo:           'images/user/user.png'
when@prod:
    parameters:
        images:
            logo:           'images/user/user.png'
